[package]
name = "dpress_sandbox"
version = "0.1.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]

[dependencies]
rand = "0.6.1"
statistical = "0.1.1"
sensulator = "0.1.0"

[patch.crates-io]
sensulator = { git = "https://github.com/tstellanova/sensulator"  }